In [139]:
import numpy as np

input

In [140]:
x = np.array([-0.3,-0.1,-0.2,-0.2])

# 1 hidden layers

weight for input

In [141]:
w1 = np.array(
    [
        [0.3,0.4,0.3],
        [0.5,0.2,0.3],
        [0.2,0.6,0.2],
        [0.1,0.3,0.6]
    ]
)

w1_t = w1.T

In [142]:
b1 = np.array([[0.1,0.1,0.1]])

# 2 hidden layer

In [143]:
w2 = np.array(
    [
        [0.4,0.6],
        [0.3,0.7],
        [0.8,0.2]
    ]
)

w2_t = w2.T

In [144]:
b2 = np.array([0.1,0.1])

Output layer

In [145]:
w3 = np.array(
    [
        [0.4],
        [0.5]
    ]
)

w3_t = w3.T


In [146]:
b3 = np.array([[0.1]])

## sigmoid function

In [147]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [148]:

print(f"{sigmoid(100):.8f}")


1.00000000


# Forward propagate

In [149]:
x

array([-0.300000, -0.100000, -0.200000, -0.200000])

In [150]:
w1_t

array([[0.300000, 0.500000, 0.200000, 0.100000],
       [0.400000, 0.200000, 0.600000, 0.300000],
       [0.300000, 0.300000, 0.200000, 0.600000]])

In [151]:
o1 = w1_t @ x + b1

In [152]:
o1_sig = sigmoid(o1)

next layer

In [153]:
o1_sig[0]

array([0.475021, 0.445221, 0.455121])

In [154]:
o2 = w2_t.dot(o1_sig[0]) + b2

In [155]:
o2

array([0.787671, 0.787691])

In [156]:
o2_sig = sigmoid(o2)

o2_sig

array([0.687331, 0.687335])

Next layer

In [157]:
o3 = w3_t @ o2_sig + b3

In [158]:
y_hat = sigmoid(o3)

In [159]:
y_hat

array([[0.672299]])

In [160]:
True if y_hat > 0.5 else False

True