# Forward Propagation

In [69]:
import numpy as np

## Layer 01

In [70]:
x = np.array([6,8,4,0])

In [71]:
w = np.array([
    [0.2,0.7,0.1],
    [0.3,0.2,0.5],
    [0.6,0.0,0.4],
    [0.7,0.1,0.2]

])

w1_t = w.T

In [72]:
w1_t

array([[0.2, 0.3, 0.6, 0.7],
       [0.7, 0.2, 0. , 0.1],
       [0.1, 0.5, 0.4, 0.2]])

In [73]:
b = np.array([3,5,7])

In [74]:
o1 = w1_t@x + b

In [75]:
o1

array([ 9. , 10.8, 13.2])

## Layer 02

In [76]:

w2 = np.array(
    [
        [0.3,0.7],
        [0.5,0.5],
        [0.1,0.9]
    ]
)

w_t2 = w2.T

In [77]:
w_t2

array([[0.3, 0.5, 0.1],
       [0.7, 0.5, 0.9]])

In [78]:
o1

array([ 9. , 10.8, 13.2])

In [79]:
b2 = np.array([8,3])

In [80]:
o2 = w_t2@o1 + b2

In [81]:
o2

array([17.42, 26.58])

## Layer 03

In [82]:
w3 = np.array([
    [0.8],
    [0.2]
])

w3_t = w3.T

In [83]:
w3_t

array([[0.8, 0.2]])

In [84]:
o2

array([17.42, 26.58])

In [85]:
b = 5


In [86]:
y_hat = w3_t@o2 + b

In [87]:
print("Output: ",y_hat)

Output:  [24.252]
