In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

2 Features -> Dense Layer(4 neurons) -> Dense Layer(1 neuron)

In [2]:
x = tf.constant([[2.0,3.0],
 [1.0,4.0],
  [3.0,2.0],
   [4.0,1.0]])

y = tf.constant([10.0,9.0,11.0,12.0])

In [3]:
model = keras.Sequential(
    [
        layers.Dense(4, input_shape=(2,),activation='relu'),
        layers.Dense(1)
    ]
)

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [4]:
model.compile(optimizer='sgd',loss='mse')

In [5]:
history = model.fit(x,y,epochs = 100,verbose=1)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 428ms/step - loss: 88.8043
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 33.9367
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.7692
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.2212
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.1036
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0543
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0343
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0236
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0172
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0130
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0101
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0081
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0067
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0056
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0049
Epoch 16/100
1/1

In [16]:
y_pred = model.predict(x)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


In [9]:
model.layers[0].get_weights()

[array([[ 0.46508488,  0.39046195, -0.5733216 ,  1.4838208 ],
        [-1.0823649 , -0.9006915 , -0.11199903,  0.8641744 ]],
       dtype=float32),
 array([-0.09053337,  0.03257873,  0.        ,  0.2824528 ], dtype=float32)]

In [11]:
model.layers[1].get_weights()

[array([[-0.4894842 ],
        [ 0.36148384],
        [-0.2545179 ],
        [ 1.6583797 ]], dtype=float32),
 array([0.3183717], dtype=float32)]

In [14]:
model.trainable_variables

[<Variable path=sequential/dense/kernel, shape=(2, 4), dtype=float32, value=[[ 0.46508488  0.39046195 -0.5733216   1.4838208 ]
  [-1.0823649  -0.9006915  -0.11199903  0.8641744 ]]>,
 <Variable path=sequential/dense/bias, shape=(4,), dtype=float32, value=[-0.09053337  0.03257873  0.          0.2824528 ]>,
 <Variable path=sequential/dense_1/kernel, shape=(4, 1), dtype=float32, value=[[-0.4894842 ]
  [ 0.36148384]
  [-0.2545179 ]
  [ 1.6583797 ]]>,
 <Variable path=sequential/dense_1/bias, shape=(1,), dtype=float32, value=[0.3183717]>]

In [13]:
from sklearn.metrics import mean_squared_error as mse

In [23]:
with tf.GradientTape() as tape:

  y_pred = model(x)
  loss = tf.reduce_mean(tf.square(y_pred-y))
gradients = tape.gradient(loss,model.trainable_variables)

In [24]:
gradients

[<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[-1.4460831 ,  1.0679317 ,  0.        ,  4.154004  ],
        [-0.36152077,  0.2669829 ,  0.        , -4.153597  ]],
       dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=
 array([-3.6152077e-01,  2.6698291e-01,  0.0000000e+00,  8.1419945e-05],
       dtype=float32)>,
 <tf.Tensor: shape=(4, 1), dtype=float32, numpy=
 array([[0.5077269],
        [0.5123753],
        [0.       ],
        [1.5523517]], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([4.9114227e-05], dtype=float32)>]

In [25]:
from sklearn.datasets import make_classification


data = make_classification(1000,n_features=4,n_classes=2)

In [30]:
X = data[0]

y = data[1]

In [38]:
model = keras.Sequential(
    [
        layers.Dense(4,input_shape=(4,),activation='relu'),
        layers.Dense(4,activation='relu'),
        layers.Dense(4,activation='relu'),
        layers.Dense(1,activation='sigmoid')
    ]
)

In [39]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [40]:
model.fit(X,y,epochs=100,verbose=1)

Epoch 1/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.1740 - loss: 0.8835
Epoch 2/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2850 - loss: 0.7693
Epoch 3/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4070 - loss: 0.7103
Epoch 4/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5090 - loss: 0.6744
Epoch 5/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5450 - loss: 0.6497
Epoch 6/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6160 - loss: 0.6229
Epoch 7/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7860 - loss: 0.5836
Epoch 8/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8790 - loss: 0.5362
Epoch 9/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8780 - loss: 0.4908
Epoch 10/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8830 - loss: 0.4486
Epoch 11/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8880 - loss: 0.4100
Epoch 12/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy:

In [42]:
for layer in model.layers:
  weights = layer.get_weights()
  print(weights)

[array([[-0.14596763, -0.98407465,  0.6799822 ,  0.087853  ],
       [ 0.08068155,  0.9382243 ,  0.6425717 , -0.59651136],
       [ 0.23521821, -0.536615  , -0.23303618,  0.32561055],
       [-0.08440446,  0.54363513,  0.88453317,  1.2189188 ]],
      dtype=float32), array([-0.05361655,  0.8714916 , -0.15916745,  0.25806722], dtype=float32)]
[array([[ 0.62888664,  0.5968181 , -0.1574654 ,  0.17503986],
       [ 0.7228896 ,  0.49546647, -1.0855948 , -0.5050914 ],
       [ 0.40685058, -0.24600992,  0.86714715,  0.38908625],
       [-0.2288055 ,  0.88984483, -0.59163105,  0.6161271 ]],
      dtype=float32), array([0.16185504, 0.33475795, 0.39834172, 0.4870648 ], dtype=float32)]
[array([[ 0.56072164,  1.3708733 ,  0.43847874, -0.05723266],
       [-0.9499411 ,  0.03423132,  0.9015111 ,  0.52598256],
       [-0.49919048, -0.30187422, -0.78325266,  0.938273  ],
       [ 0.10551614, -0.11543223, -1.1553502 ,  1.0655456 ]],
      dtype=float32), array([-0.09622793,  0.13560082,  0.2575787 ,  0

In [43]:
from sklearn.datasets import make_regression

data = make_regression(1000,n_features=4,n_targets=1)


X = data[0]
y = data[1]

In [44]:
model = keras.Sequential(
    [
        layers.Dense(4,input_shape=(4,),activation='relu'),
        layers.Dense(4,activation='relu'),
        layers.Dense(4,activation='relu'),
        layers.Dense(1)
    ]
)

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [52]:
model.compile(optimizer='sgd',loss='mse')

In [53]:
model.fit(X,y,epochs=100,verbose=2)

Epoch 1/100
32/32 - 0s - 15ms/step - loss: 43995888.0000
Epoch 2/100
32/32 - 0s - 5ms/step - loss: 69515.8906
Epoch 3/100
32/32 - 0s - 4ms/step - loss: 27615.3633
Epoch 4/100
32/32 - 0s - 5ms/step - loss: 16146.2051
Epoch 5/100
32/32 - 0s - 5ms/step - loss: 12995.0742
Epoch 6/100
32/32 - 0s - 9ms/step - loss: 12158.0381
Epoch 7/100
32/32 - 0s - 3ms/step - loss: 11929.0762
Epoch 8/100
32/32 - 0s - 3ms/step - loss: 11875.8086
Epoch 9/100
32/32 - 0s - 3ms/step - loss: 11855.3135
Epoch 10/100
32/32 - 0s - 3ms/step - loss: 11850.0723
Epoch 11/100
32/32 - 0s - 3ms/step - loss: 11857.6729
Epoch 12/100
32/32 - 0s - 3ms/step - loss: 11849.3027
Epoch 13/100
32/32 - 0s - 3ms/step - loss: 11851.2754
Epoch 14/100
32/32 - 0s - 3ms/step - loss: 11850.0020
Epoch 15/100
32/32 - 0s - 3ms/step - loss: 11851.3389
Epoch 16/100
32/32 - 0s - 3ms/step - loss: 11846.3721
Epoch 17/100
32/32 - 0s - 3ms/step - loss: 11848.0684
Epoch 18/100
32/32 - 0s - 3ms/step - loss: 11846.2832
Epoch 19/100
32/32 - 0s - 3ms/ste

In [54]:
loss_fn = tf.keras.losses.MeanSquaredError()
optimizer = tf.keras.optimizers.SGD(learning_rate=0.1)
with tf.GradientTape() as tape:

  y_pred = model(X)
  loss = loss_fn(y,y_pred)
gradients = tape.gradient(loss,model.trainable_variables)

optimizer.apply_gradients(zip(gradients,model.trainable_variables))

<Variable path=SGD/iteration, shape=(), dtype=int64, value=1>

<tf.Tensor: shape=(), dtype=float32, numpy=17673.5703125>