# Tensorflow

Used for:
- numerical computation
- machine learning
- deep learning
- neural network
- GPU/TPU Computation
- Model Deployment

### Tensorflow has two major levels

#### Low level tensorflow

- tf.constant()
- tf.Variable()
- tf.matmul()
- tf.GradientTape()


#### High level keras

- tf.keras.Sequential()
- tf.keras.layers.Dense()
- model.compile()
- model.fit()
- model.evaluate()
- model.predict()




In [ ]:
pip install tensorflow

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.20.0


In [4]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [6]:
tf.config.list_physical_devices('GPU')

[]

Numpy Vs Tensorflow

In [7]:
import numpy as np

x = np.array([1,2,3])

print(x)
print(type(x))

x = tf.constant([1,2,3])

print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


A tensorflow tensor contains:

- values
- shape
- dtype

### What is tensor ?

A tensor is generalization of:

scaler -> Vector -> Matrix -> Higher-dimensional array

In [8]:
num = tf.constant(3)
print(num)

tf.Tensor(3, shape=(), dtype=int32)


In [9]:
x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [10]:
mat = tf.constant(
    [
        [3,4,2],
        [5,9,0]
    ]
)

print(mat.shape)

(2, 3)


In [11]:
mat

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 4, 2],
       [5, 9, 0]], dtype=int32)>

In [13]:
x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [12]:
tf.rank(x)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [14]:
tf.rank(num)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [15]:
tf.rank(mat)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Rank of tensors

- Scaler 0D = 0
- Vector 1D = 1
- Matrix  2D = 2
- 3D = 3
- nD = n

In [16]:
tf.zeros((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [17]:
tf.fill((3,4),5)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int32)>

In [18]:
tf.random.normal((3,4),mean=0,stddev=1)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.05822692, -1.3533207 , -0.03270591, -0.5745439 ],
       [ 0.5464884 ,  1.2404897 , -0.7841732 ,  1.009631  ],
       [ 0.73620397, -1.1392297 , -0.7088878 ,  1.0765196 ]],
      dtype=float32)>

In [19]:
tf.random.uniform((3,4),minval=0,maxval=1)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.15599108, 0.7620411 , 0.07286835, 0.98403907],
       [0.46962023, 0.94410396, 0.27222836, 0.93441725],
       [0.8204515 , 0.8482424 , 0.9394779 , 0.23774254]], dtype=float32)>

## Tensor Datatype

- tf.int32
- tf.int64
- tf.float32
- tf.float64
- tf.bool

In [22]:
y = tf.constant([3,2,5],dtype=tf.float32)

In [23]:
y

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([3., 2., 5.], dtype=float32)>

In [24]:
y.dtype

tf.float32

In [25]:
x = tf.constant([
    [45,34,56],
    [78,30,29],
    [5,9,40]
])

In [30]:
print(x[0:,1:])

tf.Tensor(
[[34 56]
 [30 29]
 [ 9 40]], shape=(3, 2), dtype=int32)


## Tensor operations

In [31]:
a = tf.constant([1,2,4])
b = tf.constant([6,9,0])

In [32]:
print(a - b)

tf.Tensor([-5 -7  4], shape=(3,), dtype=int32)


In [33]:
print(a * b)

tf.Tensor([ 6 18  0], shape=(3,), dtype=int32)


In [34]:
print(a / b)

tf.Tensor([0.16666667 0.22222222        inf], shape=(3,), dtype=float64)


#### Matrix multiplication

In [35]:
A = tf.constant(
    [
        [3,4,2],
        [4,2,4]
    ]
)

B = tf.constant(
    [
        [5,6],
        [6,9],
        [3,2]
    ]
)


print(tf.matmul(A,B))

tf.Tensor(
[[45 58]
 [44 50]], shape=(2, 2), dtype=int32)


### Tensor Reduction Operations

In [36]:
x = tf.constant([43,23,90,10])

In [37]:
tf.reduce_mean(x)

<tf.Tensor: shape=(), dtype=int32, numpy=41>

In [38]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=int32, numpy=166>

In [40]:
tf.reduce_max(x)

<tf.Tensor: shape=(), dtype=int32, numpy=90>

In [41]:
tf.reduce_min(x)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

### Reduce operations on axis

In [46]:
print(mat)

tf.Tensor(
[[3 4 2]
 [5 9 0]], shape=(2, 3), dtype=int32)


In [48]:
tf.reduce_max(mat,axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 9, 2], dtype=int32)>

# Variable Vs Constant in tensor

In [49]:
xx = tf.constant(3)
print(xx)

tf.Tensor(3, shape=(), dtype=int32)


In [50]:
xy = tf.Variable(10)

In [51]:
print(xy)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>


In [52]:
xy.assign(34)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=34>

In [53]:

print(xy)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=34>


Neural networks parameters are variables (weight and bias)

## Manual Neural network

In [56]:
x = tf.constant([2.0,3.0])

w = tf.Variable([0.5,0.8])

b = tf.Variable(0.2)

In [57]:
z = tf.reduce_sum(x*w) + b

In [58]:
z

<tf.Tensor: shape=(), dtype=float32, numpy=3.6000001430511475>

In [59]:
output = tf.nn.relu(z)

In [60]:
output

<tf.Tensor: shape=(), dtype=float32, numpy=3.6000001430511475>

## Automatic Differentiation

In [61]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
  y = x ** 2


gradient = tape.gradient(y,x)

print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)
